### ISSUE TITLE
What prompt you used to generate an entire wp theme?

### ISSUE THREAD

**Issue by uhlhosting** [cnhsn/chatgpt-wp#2]

**Comment by cnhsn** [comment]
"I want you to code a wordpress theme for me. The theme should be as simple and simple as possible. You should write each required file of the theme separately for me. I want to use it immediately without any errors."

And after that I wrote another prompt for README file. Here it is:

"Prepare a readme file that contains how to install the theme you wrote. You have to prepare it using Markdown."

**Comment by uhlhosting** [comment]
usually chatgpt stops automatically after some lines, how you continued?  thank you

**Comment by cnhsn** [comment]
If it stopped, just write "continue", then it will continue to writing code in a new line.
